"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import { Layout } from 'antd';
const { Header, Content, Footer } = Layout;

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Layout style={{minHeight:"100vh", background: "#001628", maxWidth: '100vw'}}>
            <Header
              style={{
                display: 'flex',
                alignItems: 'center',
                background: '#000'
              }}
            >
              <div className="demo-logo" />
            </Header>
            <Content
              style={{
                display: 'flex',
                borderBottom: 'solid',
                background: "#fff",
                height: '100%',
                width: '100%',
                padding: 40,
                overflowY: 'auto',
                overflowX: 'hidden'
              }}
            >
                {children}
            </Content>
            <Footer
              style={{
                textAlign: 'center',
                background: '#fff',
                color: "#001628",
                borderRadius: "0 0 10px 10px",
              }}
            >
              Scanner • {new Date().getFullYear()}
            </Footer>
          </Layout>
      </body>
    </html>
  );
}